### ISSUE TITLE
TS-1 Not found setelah log out

### ISSUE THREAD

**Issue by azie-ginanjar** [itgetlink/tokosandal#1]
![screenshot from 2018-02-01 16-58-40](https://user-images.githubusercontent.com/8444930/35672647-c5f8a944-0771-11e8-8385-d967c088c42a.png)
kondisi saat ini : setelah logout muncul halaman not found

AC: setelah logout user di redirect ke halaman home

**Comment by mutoharamin** [comment]
Urg cokot issue ieu nya? Atau dek dcokot ku nu lain?

**Comment by azie-ginanjar** [comment]
sok we min

**Comment by azie-ginanjar** [comment]
https://github.com/itgetlink/tokosandal/pull/5

---------------CLOSED----------------------
