### ISSUE TITLE
TS-6 Edit Produk Not Load

### ISSUE THREAD

**Issue by AntoBDG19** [itgetlink/tokosandal#10]
Pada halaman Admin/Produk saat melakukan perubahan pada edit dan simpan, halaman tidak berpindah dan produk tidak tersimpan
![admin_edit](https://user-images.githubusercontent.com/17784634/35956784-65246dac-0cca-11e8-8182-fa5aa5c12b69.jpg)

**Comment by AntoBDG19** [comment]
update table phpmyadmin dengan file transaksisql

**Comment by mr-troy** [comment]
delete data stok pada proses update produk
