### ISSUE TITLE
TS-12 Error message saat add to cart sebelum memilih ukuran

### ISSUE THREAD

**Issue by azie-ginanjar** [itgetlink/tokosandal#22]
Tampilkan error message berupa alert saat customer melakukan add to cart suatu produk dalam kondisi belum memilih ukuran

**Comment by AntoBDG19** [comment]
update: Hotfix/TS-12
pull requests

**Comment by azie-ginanjar** [comment]
https://github.com/itgetlink/tokosandal/pull/33
