### ISSUE TITLE
TS-13 internal server error saat customer melakukan checkout

### ISSUE THREAD

**Issue by azie-ginanjar** [itgetlink/tokosandal#23]
![iss_checkout](https://user-images.githubusercontent.com/8444930/36233719-e3107504-1219-11e8-96e9-66315d334359.png)

**Comment by mr-troy** [comment]
edit table di phpmyadmin
tambah column 'NOTLP_PENERIMA' di tabel 'transaksi'
ubah column 'ID' di tabel 'detail_transaksi' menjadi bersifat AUTO_INCREMENT (checklist di A_T )
